services:
  java-container:
    build:
      context: .
      dockerfile: Containerfile
    image: java-project-container:latest
    container_name: workshop_room
    cap_add:
      - NET_ADMIN
    networks:
      test_network:
        ipv4_address: 172.0.0.100 # Assign a static IP in the new range
    volumes:
      - .:/workbench # Mount current directory to /workbench
    working_dir: /workbench # Set the container's working directory
    #ports:
    #  - "8080:8080" # Optional: Map host port to container port
    tty: true
    stdin_open: true

networks:
  test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24

