Server_PrivateKey = "iIuSVe0MRULyAYKliT0E5jKOpYqdHAgly7zCD8cXuWo="
Listening_Port = "14856"
Server_Name = "Wireguard-v2"
Server_PublicKey = "RgN/BjT/jwgiAtrAwrXdUWR1roWg6g6Xp8PA7Ft1oX4="
Server_Address = "10.8.16.1/24"
PeerA_PrivateKey="SMpbB9NBL4yJhldu9o2BHEa7w8LuQG9U3id0w0772H8="
PeerA_AllowedIPS="10.8.16.0/24"
PeerA_Server_Address="10.8.16.2/32"
PeerA_Endpoint="172.236.185.187:14856"
PeerA_PublicKey="oqsQX49hwLVJsKUbr4OMHNMLgGdZPJ+5239OU35nVAI="
PeerA_Address="10.8.16.2/24"
PeerB_PublicKey="usVJyB2OmZkgxnc977dSRzv8XN/avlCsZuqh3kdeFkI="
PeerB_AllowedIPS="10.8.16.0/24"
PeerB_Server_Address="10.8.16.3/32"
PeerB_Address="10.8.16.3/24"
PeerB_PrivateKey="aDbGNZyf48pLiLXknPMTarehoolX0AmYIkJh23KdA0c="
PeerB_Endpoint="172.236.185.187:14856"
PeerC_PrivateKey="mGd7tsi4v2NI0dRm0YhCXHyRurn4Ht5R6UXg2zLaKkc="
PeerC_Address="10.8.16.4/24"
PeerC_AllowedIPS="10.8.16.0/24"
PeerC_Endpoint="172.236.185.187:14856"
PeerC_Server_Address="10.8.16.4/32"
PeerC_PublicKey="1RLz3pFgMMTjHIigph08nIXpdVQTDUS0BOoAzxu85gY="
PeerD_Server_Address="10.8.16.5/32"
PeerD_Endpoint="172.236.185.187:14856"
PeerD_PrivateKey="ODyyIsrsieTPQYZHJJA4vHmPouqtNF2bffCA7EfXI0s="
PeerD_PublicKey="CEXE/3KP05yFeql/toZpEsmZEngwSdCGBsT/N0f7WWs="
PeerD_Address="10.8.16.5/24"
PeerD_AllowedIPS="10.8.16.0/24"
PeerE_PublicKey="p1h9GVCz7bAKaGJFvtNZEC8Py69F4+VbQtxcET3HgGc="
PeerE_Address="10.8.16.6/24"
PeerE_Server_Address="10.8.16.6/32"
PeerE_PrivateKey="WCJUrB6yC6+XC2WSCZRhX5V7N+TfLy133NcOUeymxn4="
PeerE_Endpoint="172.236.185.187:14856"
PeerE_AllowedIPS="10.8.16.0/24"
PeerF_AllowedIPS="10.8.16.0/24"
PeerF_Endpoint="172.236.185.187:14856"
PeerF_Address="10.8.16.7/24"
PeerF_PublicKey="6SEik+1HGJBuJA/JVVWDgfCt5pgfS9FAY60d+eSKWzM="
PeerF_PrivateKey="YGDhg/0toxiprj1mljXQAfZqkLZxH0/YZMV1p2HFhk0="
PeerF_Server_Address="10.8.16.7/32"
PeerG_Address="10.8.16.8/24"
PeerG_PrivateKey="qN2+JG7sXWQYUwUoglzL3GGMwmXMw4W0G9PwAtp9LmY="
PeerG_PublicKey="/+YndCnykQcurZrwe4lz3Rv+/v4+JwnWisDcKNtmGgE="
PeerG_Server_Address="10.8.16.8/32"
PeerG_AllowedIPS="10.8.16.0/24"
PeerG_Endpoint="172.236.185.187:14856"
PeerH_Address="10.8.16.9/24"
PeerH_PrivateKey="2BELOYmGoCO+Qvj6FAKFl6DHNLjc8344u8s0TB3ztUM="
PeerH_Server_Address="10.8.16.9/32"
PeerH_Endpoint="172.236.185.187:14856"
PeerH_PublicKey="dIb/CAzJU5gs5eIj/mGPxnoSfPtsjH7nRCLTlUYxY08="
PeerH_AllowedIPS="10.8.16.0/24"
PeerI_AllowedIPS="10.8.16.0/24"
PeerI_PublicKey="0U7hnZu93A/xbvjcNV/Pc6eSuEgkyFUN5ZjK1gq01RM="
PeerI_Endpoint="172.236.185.187:14856"
PeerI_PrivateKey="mE+lEmuADhNMF+z5+ISNLHt1zl7ihID3WEPw00Q1EEM="
PeerI_Server_Address="10.8.16.10/32"
PeerI_Address="10.8.16.10/24"
