Server_PrivateKey = "sL+R9FtYKIGb5XmgvZ7yyBXbBuE8fjgiIMZTgg7NdGw="
Listening_Port = "54789"
Server_Name = "Wireguard-03.alpha"
Server_PublicKey = "2mkp9Gf/lPiIjQpvFrDnUJEZHwYc/K/G7cRLRSTrFhE="
Server_Address = "10.1.1.1/24"
PeerA_PublicKey="3g/wpGviBGFvOuI7sz64ucFK2AIOOPSMLU0U0koCxiE="
PeerA_Address="10.1.1.11/24"
PeerA_PrivateKey="WF/fVEdJeXl6Z3m6zFK1kftoeIL8i9rOQ2/DWM3OJn4="
PeerA_AllowedIPS="10.1.1.0/24"
PeerA_Server_Address="10.1.1.11/32"
PeerA_Endpoint="172.2.0.101:54789"
