Server_PrivateKey = "mMyvI+qTaVGED4IFWP9v277buJTErPcxYvwcQwmK0UA="
Listening_Port = "54789"
Server_Name = "Wireguard-test"
Server_PublicKey = "qyBbux0N39a16uJOlt93gQwHWvdpGCSvweTgmz2HOAU="
Server_Address = "10.1.1.1/24"
PeerA_AllowedIPS="10.1.1.0/24"
PeerA_PrivateKey="WM9NDtE2ClLvzkjShl72gUsTXcqaFBgI/492pn1fZ3g="
PeerA_Address="10.1.1.2/24"
PeerA_PublicKey="+cLzwrZ5pDsSQ/Eu4xQ9CEn8euHD+41rOgjNwbh5cBw="
PeerA_Endpoint="172.0.0.100/24:54789"
PeerA_Server_Address="10.1.1.2/32"
