Server_PrivateKey = "iNZ2TVWLTferu29hx9fpOeLXY20XU9BIiXGqVnD113s="
Listening_Port = "54789"
Server_Name = "Wireguard-03.alpha"
Server_PublicKey = "46WFf/lIMwuwYheIT/gHEOSejp5gI8dN9WOvWGjERAs="
Server_Address = "10.1.1.1/24"
PeerA_PublicKey="VqeUtwgHuz2JNwOj977iNVi/SMgXc2As4rcwrYXfC24="
PeerA_Address="10.1.1.2/24"
PeerA_PrivateKey="SBLCnmZIDN6/rKYQs5/Pz8JJz1DYtQEqHRQHaxBxXGk="
PeerA_AllowedIPS="10.1.1.0/24"
PeerA_Server_Address="10.1.1.2/32"
PeerA_Endpoint="172.2.0.101:54789"
PeerB_Address="10.1.1.3/24"
PeerB_PrivateKey="YNoW8cdGClj/npek4G0a/6c4FVIE7o0/cW8a2AA/Ang="
PeerB_Endpoint="172.2.0.101:54789"
PeerB_PublicKey="5CB5iDyl4hRYeng6aOJOqyzHoyPeTPhqoNEVRCYA2QA="
PeerB_AllowedIPS="10.1.1.0/24"
PeerB_Server_Address="10.1.1.3/32"
