Server_PrivateKey = "yMoCbXxOomjFL1MaToh8J+ynykruYfBwJAQWcToI828="
Listening_Port = "1834"
Server_Name = "Wireguard-v2"
Server_PublicKey = "k5E3dWEGfkiAupYdlstepiPcZoRKQAOAJ7e+wv+8VDY="
Server_Address = "10.10.10.1/24"
PeerA_PublicKey="CsCAuuuNF2vpksKjnD+mBr/mc9tfcaluXFrDzWrrgwA="
PeerA_Address="10.10.10.2/24"
PeerA_PrivateKey="4CcNHr6jh2pKZVKn/N5tTbS7WKg03fonA7W8DryiCG8="
PeerA_AllowedIPS="10.10.10.0/24"
PeerA_Server_Address="10.10.10.2/32"
PeerA_Endpoint="170.187.250.239:1834"
PeerB_PublicKey="HU+OAU2Q5WsTgnHX1vCxSvECgEsEYRnKtD45FBCvHHA="
PeerB_Endpoint="170.187.250.239:1834"
PeerB_PrivateKey="CGX0zhHYAMB6O5i6o4rVbZn4QYF7b96dqDSs3Pu43FQ="
PeerB_Address="10.10.10.3/24"
PeerB_Server_Address="10.10.10.3/32"
PeerB_AllowedIPS="10.10.10.0/24"
PeerC_Endpoint="170.187.250.239:1834"
PeerC_AllowedIPS="10.10.10.0/24"
PeerC_Address="10.10.10.4/24"
PeerC_PrivateKey="GLoJRtT+CBS4aIqK7YxWpRKxt71k6yXVZmur0NDiLUA="
PeerC_PublicKey="3uuoFO66rCOg0gMheYeoP6/OJYVehHHblkKCPE4MSiA="
PeerC_Server_Address="10.10.10.4/32"
PeerD_AllowedIPS="10.10.10.0/24"
PeerD_Address="10.10.10.5/24"
PeerD_PublicKey="jrF8heYr+HhuEgQK4/Qw+E1fnZtg7ifY5KEsnmz2WlY="
PeerD_PrivateKey="sOGy4U6ThJbUlCZhf7xVVaH3iIIzIXNtz2CyTd4U/n8="
PeerD_Endpoint="170.187.250.239:1834"
PeerD_Server_Address="10.10.10.5/32"
